extends Node

enum BUILDING_FLAGS {
	LOGISTICS,
}

const GAME_IN_PROGRESS = "GAME_IN_PROGRESS"
const GAME_OVER = "GAME_OVER"
const GAME_STARTING = "GAME_STARTING"
const GAME_STARTED = "GAME_STARTED"
const GAME_EDITOR = "GAME_EDITOR"
